# Recording rules pre-compute expensive or frequently used expressions and store the result as a NEW time series, 
# additional metrics alongside already provided SpringBoot and Micrometer's metrics.
# Naming convention: level:metric:operations
#
# Used by grafana/dashboards/orders-red.json
groups:
  - name: http-red
    interval: 15s
    rules:
      # Grafana panel: RED & Business -> Request rate by endpoint
      - record: uri:http_server_requests:rate1m  
        # Value
        expr: |
          sum by (job, application, uri, method, status) (
            rate(http_server_requests_seconds_count{uri!~"/actuator.*"}[1m])
          )

      # Grafana panel: RED & Business -> Error ratio (5xx)
      - record: application:http_server_requests_errors:ratio_rate1m 
        expr: |
          (
            sum by (job, application) (rate(http_server_requests_seconds_count{uri!~"/actuator.*", status=~"5.."}[1m]))
            or
            sum by (job, application) (rate(http_server_requests_seconds_count{uri!~"/actuator.*"}[1m])) * 0
          )
          /
          sum by (job, application) (rate(http_server_requests_seconds_count{uri!~"/actuator.*"}[1m]))

      # Grafana panel: RED & Business -> Latency percentiles
      - record: application:http_server_requests_seconds:p95_1m  
        expr: |
          histogram_quantile(0.95,
            sum by (job, application, le) (
              rate(http_server_requests_seconds_bucket{uri!~"/actuator.*"}[1m])
            )
          )
